# fly.toml file generated for codeday-uploader on 2021-11-17T16:17:40-05:00

app = "codeday-uploader"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
